/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotelfinder;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author divakar
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
//        UIManager.put("ScrollPane.contentOpaque", false);
        initComponents();
        scrollPane.setOpaque(false);
        scrollPane.getViewport().setOpaque(false);
        scrollPanePanel.setBackground(new Color(255,255,255,100));
        greetTextLabel.setText("Hello " + TheHotelFinder.curUser.getName());
        hotelCardList = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePagePanel = new javax.swing.JPanel();
        line_separator = new javax.swing.JSeparator();
        greetTextLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        checkInDateLabel = new javax.swing.JLabel();
        checkOutDateLabel = new javax.swing.JLabel();
        noRoomsLabel = new javax.swing.JLabel();
        noPeopleLabel = new javax.swing.JLabel();
        noRoomsSpinner = new javax.swing.JSpinner();
        noPeopleSpinner = new javax.swing.JSpinner();
        checkInDateChooserCombo = new datechooser.beans.DateChooserCombo();
        checkOutDateChooserCombo = new datechooser.beans.DateChooserCombo();
        findHotelBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        scrollPanePanel = new javax.swing.JPanel();
        cityComboBox = new javax.swing.JComboBox<>();
        locationLabel = new javax.swing.JLabel();
        bgHydLabel = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        myAccountMenu = new javax.swing.JMenu();
        profileMenuItem = new javax.swing.JMenuItem();
        bookingsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Hotel Finder");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(new java.awt.CardLayout());

        HomePagePanel.setBackground(new java.awt.Color(245, 245, 245));
        HomePagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The Hotel Finder", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lithos Pro Regular", 0, 24))); // NOI18N
        HomePagePanel.setPreferredSize(new java.awt.Dimension(900, 800));
        HomePagePanel.setLayout(null);

        line_separator.setPreferredSize(new java.awt.Dimension(900, 10));
        HomePagePanel.add(line_separator);
        line_separator.setBounds(0, 70, 900, 10);

        greetTextLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        greetTextLabel.setForeground(new java.awt.Color(102, 102, 102));
        greetTextLabel.setText("Hello");
        HomePagePanel.add(greetTextLabel);
        greetTextLabel.setBounds(6, 42, 300, 19);

        logoutBtn.setForeground(new java.awt.Color(51, 51, 51));
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        HomePagePanel.add(logoutBtn);
        logoutBtn.setBounds(790, 30, 100, 25);

        checkInDateLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 13)); // NOI18N
        checkInDateLabel.setForeground(new java.awt.Color(51, 51, 51));
        checkInDateLabel.setText("CHECK IN ");
        HomePagePanel.add(checkInDateLabel);
        checkInDateLabel.setBounds(512, 99, 57, 15);

        checkOutDateLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 13)); // NOI18N
        checkOutDateLabel.setForeground(new java.awt.Color(51, 51, 51));
        checkOutDateLabel.setText("CHECK OUT");
        HomePagePanel.add(checkOutDateLabel);
        checkOutDateLabel.setBounds(512, 142, 64, 15);

        noRoomsLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 13)); // NOI18N
        noRoomsLabel.setForeground(new java.awt.Color(51, 51, 51));
        noRoomsLabel.setText("NUMBER OF ROOMS");
        HomePagePanel.add(noRoomsLabel);
        noRoomsLabel.setBounds(140, 140, 112, 15);

        noPeopleLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 13)); // NOI18N
        noPeopleLabel.setForeground(new java.awt.Color(51, 51, 51));
        noPeopleLabel.setText("NUMBER OF PEOPLE");
        HomePagePanel.add(noPeopleLabel);
        noPeopleLabel.setBounds(510, 190, 112, 15);
        HomePagePanel.add(noRoomsSpinner);
        noRoomsSpinner.setBounds(270, 132, 50, 30);
        HomePagePanel.add(noPeopleSpinner);
        noPeopleSpinner.setBounds(650, 182, 40, 30);
        HomePagePanel.add(checkInDateChooserCombo);
        checkInDateChooserCombo.setBounds(617, 92, 155, 22);
        HomePagePanel.add(checkOutDateChooserCombo);
        checkOutDateChooserCombo.setBounds(617, 135, 155, 22);

        findHotelBtn.setForeground(new java.awt.Color(51, 51, 51));
        findHotelBtn.setText("FIND HOTELS");
        findHotelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findHotelBtnActionPerformed(evt);
            }
        });
        HomePagePanel.add(findHotelBtn);
        findHotelBtn.setBounds(390, 260, 109, 25);

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setPreferredSize(new java.awt.Dimension(900, 552));

        scrollPanePanel.setLayout(new java.awt.GridLayout(3, 0, 10, 25));
        scrollPane.setViewportView(scrollPanePanel);

        HomePagePanel.add(scrollPane);
        scrollPane.setBounds(0, 300, 900, 600);

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hyderabad", "New Delhi", "Chennai", "Bangalore" }));
        HomePagePanel.add(cityComboBox);
        cityComboBox.setBounds(220, 90, 110, 22);

        locationLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 13)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(51, 51, 51));
        locationLabel.setText("LOCATION:");
        HomePagePanel.add(locationLabel);
        locationLabel.setBounds(150, 90, 59, 20);

        bgHydLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rohith\\Documents\\NetBeansProjects\\TheHotelFinder\\images\\charminar.jpg")); // NOI18N
        bgHydLabel.setPreferredSize(new java.awt.Dimension(900, 700));
        HomePagePanel.add(bgHydLabel);
        bgHydLabel.setBounds(0, 300, 900, 500);

        getContentPane().add(HomePagePanel, "card2");

        myAccountMenu.setText("My Account ");

        profileMenuItem.setText("My Profile");
        profileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileMenuItemActionPerformed(evt);
            }
        });
        myAccountMenu.add(profileMenuItem);

        bookingsMenuItem.setText("My Bookings");
        myAccountMenu.add(bookingsMenuItem);

        jMenuBar.add(myAccountMenu);

        helpMenu.setText("Help");
        jMenuBar.add(helpMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        setVisible(false);
        TheHotelFinder.curUser = null;
        TheHotelFinder.logRegFrame.clearFields();
        TheHotelFinder.logRegFrame.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void findHotelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findHotelBtnActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<hotelCardList.size(); i++){
            scrollPanePanel.remove((HotelCard)hotelCardList.get(0));
            hotelCardList.remove(0);
        }  
        
        String location = cityComboBox.getItemAt(cityComboBox.getSelectedIndex());
        int noRooms = (int) noRoomsSpinner.getValue();
        int noPeople = (int) noPeopleSpinner.getValue();
        String checkInDate = checkInDateChooserCombo.getText();
        String checkOutDate = checkOutDateChooserCombo.getText();
        
        if(validate(noRooms, noPeople, checkInDate, checkOutDate)){
            hotelCardList = TheHotelFinder.db.getHotels(location);
        }else{
            return;
        }            
        
        
        scrollPanePanel.setLayout(new GridLayout(hotelCardList.size(),1, 10, 25));
        
        
        System.out.println(location);
        //hotelCardList.add(new HotelCard(location));
        System.out.println("added");
        
        for(int i=0; i<hotelCardList.size(); i++){
           scrollPanePanel.add((HotelCard)hotelCardList.get(i));
        }


        ((JComponent)getContentPane()).revalidate();

    }//GEN-LAST:event_findHotelBtnActionPerformed

    private void profileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileMenuItemActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccountFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_profileMenuItemActionPerformed
    
    public boolean validate(int noRooms, int noPeople, String checkin, String checkout){
        
        
        return true;
    }
    
    private ArrayList hotelCardList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel bgHydLabel;
    private javax.swing.JMenuItem bookingsMenuItem;
    private datechooser.beans.DateChooserCombo checkInDateChooserCombo;
    private javax.swing.JLabel checkInDateLabel;
    private datechooser.beans.DateChooserCombo checkOutDateChooserCombo;
    private javax.swing.JLabel checkOutDateLabel;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JButton findHotelBtn;
    private javax.swing.JLabel greetTextLabel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JSeparator line_separator;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JMenu myAccountMenu;
    private javax.swing.JLabel noPeopleLabel;
    private javax.swing.JSpinner noPeopleSpinner;
    private javax.swing.JLabel noRoomsLabel;
    private javax.swing.JSpinner noRoomsSpinner;
    private javax.swing.JMenuItem profileMenuItem;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel scrollPanePanel;
    // End of variables declaration//GEN-END:variables
}
