/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotelfinder;

/**
 *
 * @author divakar
 */
public class HotelCard extends javax.swing.JPanel {

    /**
     * Creates new form HotelCard
     */
    public HotelCard(Hotel hotel) {
        initComponents();
        locationLabel.setText(hotel.city);
        hotelNameLabel.setText(hotel.name);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        hotelNameLabel = new javax.swing.JLabel();
        rating_label = new javax.swing.JLabel();
        ratingValueLabel = new javax.swing.JLabel();
        si_room_radbutton = new javax.swing.JRadioButton();
        do_room_radbutton = new javax.swing.JRadioButton();
        tr_room_radbutton = new javax.swing.JRadioButton();
        priceValueLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        reviewsLabel = new javax.swing.JLabel();
        deal_button = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(850, 300));

        hotelNameLabel.setFont(new java.awt.Font("Footlight MT Light", 2, 36)); // NOI18N
        hotelNameLabel.setText("THE TAJ HOTEL");

        rating_label.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        rating_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rating_label.setText("Rating");

        ratingValueLabel.setBackground(new java.awt.Color(255, 0, 51));
        ratingValueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ratingValueLabel.setText("0/5");

        buttonGroup1.add(si_room_radbutton);
        si_room_radbutton.setText("Single Room");
        si_room_radbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si_room_radbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(do_room_radbutton);
        do_room_radbutton.setText("Double Room");
        do_room_radbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                do_room_radbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(tr_room_radbutton);
        tr_room_radbutton.setText("Triple Room");
        tr_room_radbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tr_room_radbuttonActionPerformed(evt);
            }
        });

        priceValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceValueLabel.setText("VALUE");

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("PRICE");

        locationLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        locationLabel.setText("Location");

        reviewsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        reviewsLabel.setText("(65 Reviews)");

        deal_button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        deal_button.setText("View Deal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotelNameLabel)
                            .addComponent(si_room_radbutton)
                            .addComponent(do_room_radbutton)
                            .addComponent(tr_room_radbutton))
                        .addContainerGap(533, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deal_button))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(rating_label, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ratingValueLabel)
                .addGap(18, 18, 18)
                .addComponent(reviewsLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(priceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating_label)
                    .addComponent(ratingValueLabel)
                    .addComponent(reviewsLabel))
                .addGap(36, 36, 36)
                .addComponent(si_room_radbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(do_room_radbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tr_room_radbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deal_button)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void si_room_radbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si_room_radbuttonActionPerformed
        if(si_room_radbutton.isSelected()){
            priceValueLabel.setText("1000");
        }// TODO add your handling code here:
    }//GEN-LAST:event_si_room_radbuttonActionPerformed

    private void do_room_radbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_do_room_radbuttonActionPerformed
        if(do_room_radbutton.isSelected()){
            priceValueLabel.setText("2000");
        }// TODO add your handling code here:
    }//GEN-LAST:event_do_room_radbuttonActionPerformed

    private void tr_room_radbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tr_room_radbuttonActionPerformed
        if(tr_room_radbutton.isSelected()){
            priceValueLabel.setText("3000");
        }// TODO add your handling code here:
    }//GEN-LAST:event_tr_room_radbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deal_button;
    private javax.swing.JRadioButton do_room_radbutton;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceValueLabel;
    private javax.swing.JLabel ratingValueLabel;
    private javax.swing.JLabel rating_label;
    private javax.swing.JLabel reviewsLabel;
    private javax.swing.JRadioButton si_room_radbutton;
    private javax.swing.JRadioButton tr_room_radbutton;
    // End of variables declaration//GEN-END:variables
}
