/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotelfinder.frames;

import thehotelfinder.databaseutil.Hotel;
import java.util.ArrayList;

/**
 *
 * @author Rohith
 */
public class HotelFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form HotelFrame
     */
    public HotelFrame(Hotel hotel) {
        this.hotel = hotel;
        initComponents();
        hotelNameLabel.setText(hotel.getName());
        locationLabel.setText(hotel.getCity() + ", " + hotel.getState());
       
        amenitiesLabel.setText(getStringArr(hotel.getHotelDetails()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HotelPanel = new javax.swing.JPanel();
        hotelNameLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amenitiesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(710, 100, 0, 0));
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        hotelNameLabel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        hotelNameLabel.setText("Hotel Name");

        locationLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        locationLabel.setText("location");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel3.setText("Special facilities:");

        amenitiesLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        amenitiesLabel.setForeground(new java.awt.Color(102, 102, 102));
        amenitiesLabel.setText("<html> -  one<br> - two<br> - three<br>- four<br>- five</html>");

        javax.swing.GroupLayout HotelPanelLayout = new javax.swing.GroupLayout(HotelPanel);
        HotelPanel.setLayout(HotelPanelLayout);
        HotelPanelLayout.setHorizontalGroup(
            HotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelPanelLayout.createSequentialGroup()
                .addGroup(HotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HotelPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotelNameLabel)
                            .addComponent(locationLabel)
                            .addComponent(jLabel3)))
                    .addGroup(HotelPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(amenitiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        HotelPanelLayout.setVerticalGroup(
            HotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationLabel)
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(amenitiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        getContentPane().add(HotelPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String getStringArr(ArrayList arr){
        String res = "<html>";
        for(Object s:arr){
            res+=  "• " + (String)s +"<br>";
        }
        res+="</html>";
        return res;
    }

    private Hotel hotel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HotelPanel;
    private javax.swing.JLabel amenitiesLabel;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel locationLabel;
    // End of variables declaration//GEN-END:variables
}
